algoritmo "semnome"
// Função :
// Autor :
// Data : 20/04/2020
// Seção de Declarações 
var
    valor,salto, contador: inteiro

inicio
// Seção de Comandos 
      contador<- 0
      escreva("Quer contar até quanto?")
      leia(valor)
      escreva("Qual será o valor do salto?")
      leia(salto)
      enquanto (contador <=valor) faca
         escreval (contador)
         contador <- contador + salto
      fimenquanto
      escreva("Terminei de contar")
      
fimalgoritmo
