algoritmo "semnome"
// Função :
// Autor :
// Data : 22/04/2020
// Seção de Declarações 
var
   x, y: inteiro
procedimento soma (var a, b: inteiro)
inicio
      a <- a + 1
      a <- b + 2
      escreval("valor de a = ", a)
      escreval("Valor de b = ", b)
      escreval("Soma de a + b = ", a+b)
fimprocedimento
inicio
// Seção de Comandos 
   x <- 4
   y <- 8
   soma (x, y)
   escreval("Valor de x = ", x)
   escreval("Valor de y = ", y)
fimalgoritmo
